// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type BlogPostDocumentDataSlicesSlice = never;

/**
 * Content for blog post documents
 */
interface BlogPostDocumentData {
  /**
   *  Blog title field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.blog_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blog_title: prismic.KeyTextField;

  /**
   * Date posted field in *blog post*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.date_posted
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date_posted: prismic.TimestampField;

  /**
   * Slice Zone field in *blog post*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<BlogPostDocumentDataSlicesSlice> /**
   * Meta Description field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: blog_post.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *blog post*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_post.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *blog post*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: blog_post.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * blog post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<BlogPostDocumentData>,
    "blog_post",
    Lang
  >;

interface FooterDocumentData {}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<FooterDocumentData>,
    "footer",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | ReasonsForCoachingSlice
  | ServiceSectionSlice
  | SessionSchedulingSlice
  | NewsletterSectionSlice
  | ImageCarouselSlice
  | HeroBannerSlice
  | ContactSectionSlice
  | BlogSliderSlice
  | AboutSectionSlice;

/**
 * Content for home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Whatsapp field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.whatsapp
   * - **Tab**: Social media links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  whatsapp: prismic.LinkField;

  /**
   * Facebook field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.facebook
   * - **Tab**: Social media links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  facebook: prismic.LinkField;

  /**
   * Twitter field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.twitter
   * - **Tab**: Social media links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  twitter: prismic.LinkField;

  /**
   * Instagram field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.instagram
   * - **Tab**: Social media links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;

  /**
   * Linkedin field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.linkedin
   * - **Tab**: Social media links
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  linkedin: prismic.LinkField /**
   * Your business name field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.your_business_name
   * - **Tab**: General information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  your_business_name: prismic.KeyTextField;

  /**
   * Your business motto field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.your_business_motto
   * - **Tab**: General information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  your_business_motto: prismic.KeyTextField;

  /**
   * Location (City, State, Country) field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.location
   * - **Tab**: General information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Email address field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.email_address
   * - **Tab**: General information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email_address: prismic.KeyTextField;

  /**
   * Phone number field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.phone_number
   * - **Tab**: General information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  phone_number: prismic.KeyTextField;

  /**
   * Hours opened field in *home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.hours_opened
   * - **Tab**: General information
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  hours_opened: prismic.RichTextField;

  /**
   * Copyright label field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.copyright_label
   * - **Tab**: General information
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  copyright_label: prismic.KeyTextField /**
   * API Link field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.api_link
   * - **Tab**: Newsletter
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  api_link: prismic.LinkField;

  /**
   * Newsletter title field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.newsletter_title
   * - **Tab**: Newsletter
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_title: prismic.KeyTextField;

  /**
   * Newsletter description field in *home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.newsletter_description
   * - **Tab**: Newsletter
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  newsletter_description: prismic.KeyTextField /**
   * Calendar link field in *home*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: home.calendar_link
   * - **Tab**: Consultation
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */;
  calendar_link: prismic.LinkField;
}

/**
 * home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
  /**
   * Label for consultation field in *Menu*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.label_for_consultation
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label_for_consultation: prismic.KeyTextField;

  /**
   * Logo title field in *Menu*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.logo_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_title: prismic.ImageField<never>;

  /**
   * Title field in *Menu*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: menu.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

export type AllDocumentTypes =
  | BlogPostDocument
  | FooterDocument
  | HomeDocument
  | MenuDocument;

/**
 * Primary content in *AboutSection → Primary*
 */
export interface AboutSectionSliceDefaultPrimary {
  /**
   * Title field in *AboutSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Meet your coach, Ann
   * - **API ID Path**: about_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * CTA label field in *AboutSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Free consultation label field in *AboutSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.free_consultation_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  free_consultation_label: prismic.KeyTextField;

  /**
   * Anns profile picture field in *AboutSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.anns_profile_picture
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  anns_profile_picture: prismic.ImageField<never>;

  /**
   * Credential symbol field in *AboutSection → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.primary.credential_symbol
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  credential_symbol: prismic.ImageField<never>;
}

/**
 * Primary content in *AboutSection → Items*
 */
export interface AboutSectionSliceDefaultItem {
  /**
   * Paragraph field in *AboutSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * quote field field in *AboutSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about_section.items[].quote_field
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  quote_field: prismic.RichTextField;
}

/**
 * Default variation for AboutSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AboutSectionSliceDefaultPrimary>,
  Simplify<AboutSectionSliceDefaultItem>
>;

/**
 * Slice variation for *AboutSection*
 */
type AboutSectionSliceVariation = AboutSectionSliceDefault;

/**
 * AboutSection Shared Slice
 *
 * - **API ID**: `about_section`
 * - **Description**: AboutSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type AboutSectionSlice = prismic.SharedSlice<
  "about_section",
  AboutSectionSliceVariation
>;

/**
 * Primary content in *BlogSlider → Items*
 */
export interface BlogSliderSliceDefaultItem {
  /**
   * Blog photo field in *BlogSlider → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slider.items[].blog_photo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  blog_photo: prismic.ImageField<never>;

  /**
   * Blog title field in *BlogSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slider.items[].blog_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blog_title: prismic.KeyTextField;

  /**
   * Blog date and topic field in *BlogSlider → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slider.items[].blog_date_and_topic
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  blog_date_and_topic: prismic.KeyTextField;

  /**
   * Link to blog field in *BlogSlider → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slider.items[].link_to_blog
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link_to_blog: prismic.LinkToMediaField;

  /**
   * Blog id field in *BlogSlider → Items*
   *
   * - **Field Type**: Content Relationship
   * - **Placeholder**: *None*
   * - **API ID Path**: blog_slider.items[].blog_id
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  blog_id: prismic.ContentRelationshipField;
}

/**
 * Default variation for BlogSlider Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSliderSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<BlogSliderSliceDefaultItem>
>;

/**
 * Slice variation for *BlogSlider*
 */
type BlogSliderSliceVariation = BlogSliderSliceDefault;

/**
 * BlogSlider Shared Slice
 *
 * - **API ID**: `blog_slider`
 * - **Description**: BlogSlider
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type BlogSliderSlice = prismic.SharedSlice<
  "blog_slider",
  BlogSliderSliceVariation
>;

/**
 * Primary content in *ContactSection → Primary*
 */
export interface ContactSectionSliceDefaultPrimary {
  /**
   * Title field in *ContactSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *ContactSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  subtitle: prismic.RichTextField;

  /**
   * Contact information title field in *ContactSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.primary.contact_information_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_information_title: prismic.KeyTextField;

  /**
   * Contact information description field in *ContactSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.primary.contact_information_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  contact_information_description: prismic.RichTextField;

  /**
   * Show social media field in *ContactSection → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: contact_section.primary.show_social_media
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show_social_media: prismic.BooleanField;
}

/**
 * Primary content in *ContactSection → Items*
 */
export interface ContactSectionSliceDefaultItem {
  /**
   * Inquiry option field in *ContactSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_section.items[].inquiry_option
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  inquiry_option: prismic.KeyTextField;
}

/**
 * Default variation for ContactSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSectionSliceDefaultPrimary>,
  Simplify<ContactSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ContactSection*
 */
type ContactSectionSliceVariation = ContactSectionSliceDefault;

/**
 * ContactSection Shared Slice
 *
 * - **API ID**: `contact_section`
 * - **Description**: ContactSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ContactSectionSlice = prismic.SharedSlice<
  "contact_section",
  ContactSectionSliceVariation
>;

/**
 * Primary content in *HeroBanner → Primary*
 */
export interface HeroBannerSliceDefaultPrimary {
  /**
   * Background Media field in *HeroBanner → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.background_media
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  background_media: prismic.LinkToMediaField;

  /**
   * Title field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.RichTextField;

  /**
   * Title description field in *HeroBanner → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.title_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title_description: prismic.RichTextField;

  /**
   * CTA Label field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.cta_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_label: prismic.KeyTextField;

  /**
   * Contact Button Label field in *HeroBanner → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.primary.contact_button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  contact_button_label: prismic.KeyTextField;
}

/**
 * Primary content in *HeroBanner → Items*
 */
export interface HeroBannerSliceDefaultItem {
  /**
   * credentials field in *HeroBanner → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_banner.items[].credentials
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  credentials: prismic.KeyTextField;
}

/**
 * Default variation for HeroBanner Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroBannerSliceDefaultPrimary>,
  Simplify<HeroBannerSliceDefaultItem>
>;

/**
 * Slice variation for *HeroBanner*
 */
type HeroBannerSliceVariation = HeroBannerSliceDefault;

/**
 * HeroBanner Shared Slice
 *
 * - **API ID**: `hero_banner`
 * - **Description**: HeroBanner
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroBannerSlice = prismic.SharedSlice<
  "hero_banner",
  HeroBannerSliceVariation
>;

/**
 * Primary content in *ImageCarousel → Items*
 */
export interface ImageCarouselSliceDefaultItem {
  /**
   * Image field in *ImageCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_carousel.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Default variation for ImageCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<ImageCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *ImageCarousel*
 */
type ImageCarouselSliceVariation = ImageCarouselSliceDefault;

/**
 * ImageCarousel Shared Slice
 *
 * - **API ID**: `image_carousel`
 * - **Description**: ImageCarousel
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageCarouselSlice = prismic.SharedSlice<
  "image_carousel",
  ImageCarouselSliceVariation
>;

/**
 * Primary content in *NewsletterSection → Primary*
 */
export interface NewsletterSectionSliceDefaultPrimary {
  /**
   * Title field in *NewsletterSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *NewsletterSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: newsletter_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for NewsletterSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<NewsletterSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *NewsletterSection*
 */
type NewsletterSectionSliceVariation = NewsletterSectionSliceDefault;

/**
 * NewsletterSection Shared Slice
 *
 * - **API ID**: `newsletter_section`
 * - **Description**: NewsletterSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type NewsletterSectionSlice = prismic.SharedSlice<
  "newsletter_section",
  NewsletterSectionSliceVariation
>;

/**
 * Primary content in *ReasonsForCoaching → Primary*
 */
export interface ReasonsForCoachingSliceDefaultPrimary {
  /**
   * Image field in *ReasonsForCoaching → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons_for_coaching.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Subtitle field in *ReasonsForCoaching → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons_for_coaching.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Title field in *ReasonsForCoaching → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons_for_coaching.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description title field in *ReasonsForCoaching → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons_for_coaching.primary.descriptiont_itle
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  descriptiont_itle: prismic.RichTextField;
}

/**
 * Primary content in *ReasonsForCoaching → Items*
 */
export interface ReasonsForCoachingSliceDefaultItem {
  /**
   * Logo field in *ReasonsForCoaching → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons_for_coaching.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Reason description field in *ReasonsForCoaching → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons_for_coaching.items[].reason_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  reason_description: prismic.RichTextField;

  /**
   * Reason title field in *ReasonsForCoaching → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: reasons_for_coaching.items[].reason_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  reason_title: prismic.KeyTextField;
}

/**
 * Default variation for ReasonsForCoaching Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReasonsForCoachingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReasonsForCoachingSliceDefaultPrimary>,
  Simplify<ReasonsForCoachingSliceDefaultItem>
>;

/**
 * Slice variation for *ReasonsForCoaching*
 */
type ReasonsForCoachingSliceVariation = ReasonsForCoachingSliceDefault;

/**
 * ReasonsForCoaching Shared Slice
 *
 * - **API ID**: `reasons_for_coaching`
 * - **Description**: ReasonsForCoaching
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReasonsForCoachingSlice = prismic.SharedSlice<
  "reasons_for_coaching",
  ReasonsForCoachingSliceVariation
>;

/**
 * Primary content in *ServiceSection → Primary*
 */
export interface ServiceSectionSliceDefaultPrimary {
  /**
   * Title field in *ServiceSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *ServiceSection → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ServiceSection → Items*
 */
export interface ServiceSectionSliceDefaultItem {
  /**
   * Service image field in *ServiceSection → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.items[].service_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  service_image: prismic.ImageField<never>;

  /**
   * Service title field in *ServiceSection → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.items[].service_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service_title: prismic.KeyTextField;

  /**
   * Service description field in *ServiceSection → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: service_section.items[].service_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  service_description: prismic.RichTextField;
}

/**
 * Default variation for ServiceSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ServiceSectionSliceDefaultPrimary>,
  Simplify<ServiceSectionSliceDefaultItem>
>;

/**
 * Slice variation for *ServiceSection*
 */
type ServiceSectionSliceVariation = ServiceSectionSliceDefault;

/**
 * ServiceSection Shared Slice
 *
 * - **API ID**: `service_section`
 * - **Description**: ServiceSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ServiceSectionSlice = prismic.SharedSlice<
  "service_section",
  ServiceSectionSliceVariation
>;

/**
 * Primary content in *SessionScheduling → Primary*
 */
export interface SessionSchedulingSliceDefaultPrimary {
  /**
   * Title field in *SessionScheduling → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: session_scheduling.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *SessionScheduling → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: session_scheduling.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *SessionScheduling → Items*
 */
export interface SessionSchedulingSliceDefaultItem {
  /**
   * Button_color field in *SessionScheduling → Items*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: White background, green border, green text
   * - **API ID Path**: session_scheduling.items[].button_color
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  button_color: prismic.SelectField<
    | "White background, green border, green text"
    | "Green background, white text"
    | "Blue background, white text",
    "filled"
  >;

  /**
   * Button link field in *SessionScheduling → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: session_scheduling.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Button text field in *SessionScheduling → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: session_scheduling.items[].button_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_text: prismic.KeyTextField;
}

/**
 * Default variation for SessionScheduling Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SessionSchedulingSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SessionSchedulingSliceDefaultPrimary>,
  Simplify<SessionSchedulingSliceDefaultItem>
>;

/**
 * Slice variation for *SessionScheduling*
 */
type SessionSchedulingSliceVariation = SessionSchedulingSliceDefault;

/**
 * SessionScheduling Shared Slice
 *
 * - **API ID**: `session_scheduling`
 * - **Description**: SessionScheduling
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SessionSchedulingSlice = prismic.SharedSlice<
  "session_scheduling",
  SessionSchedulingSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      BlogPostDocument,
      BlogPostDocumentData,
      BlogPostDocumentDataSlicesSlice,
      FooterDocument,
      FooterDocumentData,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      MenuDocument,
      MenuDocumentData,
      AllDocumentTypes,
      AboutSectionSlice,
      AboutSectionSliceDefaultPrimary,
      AboutSectionSliceDefaultItem,
      AboutSectionSliceVariation,
      AboutSectionSliceDefault,
      BlogSliderSlice,
      BlogSliderSliceDefaultItem,
      BlogSliderSliceVariation,
      BlogSliderSliceDefault,
      ContactSectionSlice,
      ContactSectionSliceDefaultPrimary,
      ContactSectionSliceDefaultItem,
      ContactSectionSliceVariation,
      ContactSectionSliceDefault,
      HeroBannerSlice,
      HeroBannerSliceDefaultPrimary,
      HeroBannerSliceDefaultItem,
      HeroBannerSliceVariation,
      HeroBannerSliceDefault,
      ImageCarouselSlice,
      ImageCarouselSliceDefaultItem,
      ImageCarouselSliceVariation,
      ImageCarouselSliceDefault,
      NewsletterSectionSlice,
      NewsletterSectionSliceDefaultPrimary,
      NewsletterSectionSliceVariation,
      NewsletterSectionSliceDefault,
      ReasonsForCoachingSlice,
      ReasonsForCoachingSliceDefaultPrimary,
      ReasonsForCoachingSliceDefaultItem,
      ReasonsForCoachingSliceVariation,
      ReasonsForCoachingSliceDefault,
      ServiceSectionSlice,
      ServiceSectionSliceDefaultPrimary,
      ServiceSectionSliceDefaultItem,
      ServiceSectionSliceVariation,
      ServiceSectionSliceDefault,
      SessionSchedulingSlice,
      SessionSchedulingSliceDefaultPrimary,
      SessionSchedulingSliceDefaultItem,
      SessionSchedulingSliceVariation,
      SessionSchedulingSliceDefault,
    };
  }
}
