// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  about_section: dynamic(() => import("./AboutSection")),
  blog_slider: dynamic(() => import("./BlogSlider")),
  contact_section: dynamic(() => import("./ContactSection")),
  hero_banner: dynamic(() => import("./HeroBanner")),
  image_carousel: dynamic(() => import("./ImageCarousel")),
  newsletter_section: dynamic(() => import("./NewsletterSection")),
  reasons_for_coaching: dynamic(() => import("./ReasonsForCoaching")),
  service_section: dynamic(() => import("./ServiceSection")),
  session_scheduling: dynamic(() => import("./SessionScheduling")),
};
